int A = 5;
int B = 7;
int A1 = 2;
int B1 = 10;
int A2 = -9;
int B2 = -3;
int max = A;
int max1 = A1;
int max2 = A2;
if (A > max) max = A;
if (B > max) max = B;
if (A1 > max1) max1 = A1;
if (B1 > max1) max1 = B1;
if (A2 > max2) max2 = A2;
if (B2 > max2) max2 = B2;
Console.Write ("max = ");
Console.WriteLine(max);
Console.Write ("max1 = ");
Console.WriteLine(max1);
Console.Write ("max2 = ");
Console.WriteLine(max2);
